//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventManagement.BusinessLogic.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation template uploaded.
        /// </summary>
        public static string ADD_ACCREDITATION_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_ACCREDITATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement added.
        /// </summary>
        public static string ADD_ANNOUNCEMENT_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_ANNOUNCEMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event added.
        /// </summary>
        public static string ADD_EVENT_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_EVENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest added.
        /// </summary>
        public static string ADD_GUEST_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_GUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel booking added.
        /// </summary>
        public static string ADD_HOTEL_BOOKING_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_HOTEL_BOOKING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel added.
        /// </summary>
        public static string ADD_HOTEL_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_HOTEL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization added.
        /// </summary>
        public static string ADD_ORGANIZATION_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_ORGANIZATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationTypes added.
        /// </summary>
        public static string ADD_ORGANIZATIONTYPES_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_ORGANIZATIONTYPES_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment provider added.
        /// </summary>
        public static string ADD_PAYMENT_PROVIDER_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_PAYMENT_PROVIDER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff added.
        /// </summary>
        public static string ADD_STAFF_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_STAFF_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription added.
        /// </summary>
        public static string ADD_SUBSCRIPTION_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_SUBSCRIPTION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction added.
        /// </summary>
        public static string ADD_TRANSCTION_DETAIL {
            get {
                return ResourceManager.GetString("ADD_TRANSCTION_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fees added.
        /// </summary>
        public static string ADD_VISA_FEES_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_VISA_FEES_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa added.
        /// </summary>
        public static string ADD_VISA_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_VISA_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount updated.
        /// </summary>
        public static string AMOUNT_UPDATED {
            get {
                return ResourceManager.GetString("AMOUNT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket assigned.
        /// </summary>
        public static string ASSIGN_TICKET_SUCCESS {
            get {
                return ResourceManager.GetString("ASSIGN_TICKET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one role is required..
        /// </summary>
        public static string ATLEAST_ONE_ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("ATLEAST_ONE_ROLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one room is required..
        /// </summary>
        public static string ATLEAST_ONE_ROOM_REQUIRED {
            get {
                return ResourceManager.GetString("ATLEAST_ONE_ROOM_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank receipt uploaded.
        /// </summary>
        public static string BANK_RECEIPT_UPLOADED {
            get {
                return ResourceManager.GetString("BANK_RECEIPT_UPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking not found.
        /// </summary>
        public static string BOOKING_NOT_FOUND {
            get {
                return ResourceManager.GetString("BOOKING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking cancelled {1} {2}Refund of {0} USD will be credited to your wallet shortly..
        /// </summary>
        public static string CANCEL_BOOKING_SUCCESS {
            get {
                return ResourceManager.GetString("CANCEL_BOOKING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest cancelled.
        /// </summary>
        public static string CANCEL_GUEST_SUCCESS {
            get {
                return ResourceManager.GetString("CANCEL_GUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription cancelled.
        /// </summary>
        public static string CANCEL_SUBSCRIPTION {
            get {
                return ResourceManager.GetString("CANCEL_SUBSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket closed.
        /// </summary>
        public static string CLOSE_TICKET_SUCCESS {
            get {
                return ResourceManager.GetString("CLOSE_TICKET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contacting us. Your message has been received..
        /// </summary>
        public static string CONTACT_US {
            get {
                return ResourceManager.GetString("CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization registered. Your account will be approved by the team soon..
        /// </summary>
        public static string CREATE_ORGANIZATION_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_ORGANIZATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support ticket added.
        /// </summary>
        public static string CREATE_TICKET {
            get {
                return ResourceManager.GetString("CREATE_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string CUSTOMER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CUSTOMER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event with this name already exists..
        /// </summary>
        public static string DATABASE_ERROR_1001 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has already started and cannot be edited..
        /// </summary>
        public static string DATABASE_ERROR_1002 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found..
        /// </summary>
        public static string DATABASE_ERROR_1003 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string DATABASE_ERROR_1004 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect..
        /// </summary>
        public static string DATABASE_ERROR_1005 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string DATABASE_ERROR_1006 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An organization with this name already exists..
        /// </summary>
        public static string DATABASE_ERROR_1007 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update payment configuration because there are ongoing events associated with this payment provider..
        /// </summary>
        public static string DATABASE_ERROR_1008 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization does not exist.
        /// </summary>
        public static string DATABASE_ERROR_1009 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization payment provider does not exist.
        /// </summary>
        public static string DATABASE_ERROR_1010 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff with this email already exists.
        /// </summary>
        public static string DATABASE_ERROR_1011 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel not found.
        /// </summary>
        public static string DATABASE_ERROR_1012 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string DATABASE_ERROR_1013 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your draft order before creating a new one..
        /// </summary>
        public static string DATABASE_ERROR_1014 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fees not found.
        /// </summary>
        public static string DATABASE_ERROR_1015 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed: This hotel is currently booked and cannot be deleted..
        /// </summary>
        public static string DATABASE_ERROR_1016 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed: This room has active bookings..
        /// </summary>
        public static string DATABASE_ERROR_1017 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed: This event has active bookings..
        /// </summary>
        public static string DATABASE_ERROR_1018 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details Already Saved.
        /// </summary>
        public static string DATABASE_ERROR_1019 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest not found..
        /// </summary>
        public static string DATABASE_ERROR_1020 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup currency before creating event..
        /// </summary>
        public static string DATABASE_ERROR_1021 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found for the given GuestId..
        /// </summary>
        public static string DATABASE_ERROR_1022 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old guestId does not exist.
        /// </summary>
        public static string DATABASE_ERROR_1023 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New guestId does not exist.
        /// </summary>
        public static string DATABASE_ERROR_1024 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Event found for the given OrderId.
        /// </summary>
        public static string DATABASE_ERROR_1025 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No penalty information found for the given eventId.
        /// </summary>
        public static string DATABASE_ERROR_1026 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldGuestId and NewGuestId do not belong to the same order.
        /// </summary>
        public static string DATABASE_ERROR_1027 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking not found.
        /// </summary>
        public static string DATABASE_ERROR_1028 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationType not found.
        /// </summary>
        public static string DATABASE_ERROR_1029 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest is already assigned to another hotel..
        /// </summary>
        public static string DATABASE_ERROR_1030 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket is already closed.
        /// </summary>
        public static string DATABASE_ERROR_1031 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reply to a closed ticket.
        /// </summary>
        public static string DATABASE_ERROR_1032 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ticket.
        /// </summary>
        public static string DATABASE_ERROR_1033 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not found.
        /// </summary>
        public static string DATABASE_ERROR_1034 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking already canceled.
        /// </summary>
        public static string DATABASE_ERROR_1035 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel already exists.
        /// </summary>
        public static string DATABASE_ERROR_1036 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization not found.
        /// </summary>
        public static string DATABASE_ERROR_1037 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff not found.
        /// </summary>
        public static string DATABASE_ERROR_1038 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportNumber required.
        /// </summary>
        public static string DATABASE_ERROR_1039 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event has bookings and cannot be edited.
        /// </summary>
        public static string DATABASE_ERROR_1040 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket is closed and cannot be assigned..
        /// </summary>
        public static string DATABASE_ERROR_1041 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only support staff or admin can assign tickets..
        /// </summary>
        public static string DATABASE_ERROR_1042 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of guests must be between the minimum and maximum occupancy.
        /// </summary>
        public static string DATABASE_ERROR_1043 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount is already paid.
        /// </summary>
        public static string DATABASE_ERROR_1044 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization subscription is not active.
        /// </summary>
        public static string DATABASE_ERROR_1045 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement not found.
        /// </summary>
        public static string DATABASE_ERROR_1046 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event limit exceeded.
        /// </summary>
        public static string DATABASE_ERROR_1047 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency update is not allowed.
        /// </summary>
        public static string DATABASE_ERROR_1048 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid otp please try again..
        /// </summary>
        public static string DATABASE_ERROR_1049 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not exist..
        /// </summary>
        public static string DATABASE_ERROR_1050 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingId not found.
        /// </summary>
        public static string DATABASE_ERROR_1051 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest is already in draft.
        /// </summary>
        public static string DATABASE_ERROR_1052 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainName already exists.
        /// </summary>
        public static string DATABASE_ERROR_1053 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is more than unpaid amount.
        /// </summary>
        public static string DATABASE_ERROR_1054 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email ID is not registered with our account. Please check and try again or sign up for a new account..
        /// </summary>
        public static string DATABASE_ERROR_1055 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This staff member is assigned to active tickets and cannot be deleted..
        /// </summary>
        public static string DATABASE_ERROR_1056 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order you are trying to cancel has already been canceled..
        /// </summary>
        public static string DATABASE_ERROR_1057 {
            get {
                return ResourceManager.GetString("DATABASE_ERROR_1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline is required.
        /// </summary>
        public static string DEADLINE_REQUIRED_FOR_PENALTY {
            get {
                return ResourceManager.GetString("DEADLINE_REQUIRED_FOR_PENALTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation info deleted.
        /// </summary>
        public static string DELETE_ACCOMMODATION_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_ACCOMMODATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement deleted.
        /// </summary>
        public static string DELETE_ANNOUNCEMENT_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_ANNOUNCEMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted.
        /// </summary>
        public static string DELETE_EVENT_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_EVENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest deleted.
        /// </summary>
        public static string DELETE_GUEST_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_GUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel deleted.
        /// </summary>
        public static string DELETE_HOTEL_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_HOTEL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization deleted.
        /// </summary>
        public static string DELETE_ORGANIZATION_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_ORGANIZATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationType deleted.
        /// </summary>
        public static string DELETE_ORGANIZATIONTYPE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_ORGANIZATIONTYPE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff deleted.
        /// </summary>
        public static string DELETE_STAFF_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_STAFF_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide either id or domain..
        /// </summary>
        public static string ID_DOMAIN_REQUIRED {
            get {
                return ResourceManager.GetString("ID_DOMAIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is no longer active..
        /// </summary>
        public static string INACTIVE_ACCOUNT {
            get {
                return ResourceManager.GetString("INACTIVE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect.
        /// </summary>
        public static string INCORRECT_EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("INCORRECT_EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of guests must be between the minimum and maximum occupancy..
        /// </summary>
        public static string INVALID_GUEST_OCCUPANCY {
            get {
                return ResourceManager.GetString("INVALID_GUEST_OCCUPANCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plan does not exist.
        /// </summary>
        public static string INVALID_PLAN {
            get {
                return ResourceManager.GetString("INVALID_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription does not exist.
        /// </summary>
        public static string INVALID_SUBSCRIPTION {
            get {
                return ResourceManager.GetString("INVALID_SUBSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_TOKEN.
        /// </summary>
        public static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationId is required..
        /// </summary>
        public static string ORGANIZATION_REQUIRED {
            get {
                return ResourceManager.GetString("ORGANIZATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp send.
        /// </summary>
        public static string OTP_SUCCESS {
            get {
                return ResourceManager.GetString("OTP_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment setup is incomplete. The organization needs to configure payment details to continue..
        /// </summary>
        public static string PAYMENT_SETUP_MISSING {
            get {
                return ResourceManager.GetString("PAYMENT_SETUP_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your organization&apos;s status is pending or inactive. Kindly reach out to the administrator for assistance..
        /// </summary>
        public static string PENDING_ORGANIZATION {
            get {
                return ResourceManager.GetString("PENDING_ORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest replaced.
        /// </summary>
        public static string REPLACE_GUEST_SUCCESS {
            get {
                return ResourceManager.GetString("REPLACE_GUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent.
        /// </summary>
        public static string REPLY_TICKET_SUCCESS {
            get {
                return ResourceManager.GetString("REPLY_TICKET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in  successfully..
        /// </summary>
        public static string SIGNIN_SUCCESS {
            get {
                return ResourceManager.GetString("SIGNIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer logged in  successfully..
        /// </summary>
        public static string SIGNIN1_SUCCESS {
            get {
                return ResourceManager.GetString("SIGNIN1_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resgistered successfully..
        /// </summary>
        public static string SIGNUP_SUCCESS {
            get {
                return ResourceManager.GetString("SIGNUP_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status update.
        /// </summary>
        public static string STATUS_UPDATE {
            get {
                return ResourceManager.GetString("STATUS_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. please try again later.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation template update.
        /// </summary>
        public static string UPDATE__ACCREDITATION_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_ ACCREDITATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement updated.
        /// </summary>
        public static string UPDATE_ANNOUNCEMENT_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_ANNOUNCEMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event updated.
        /// </summary>
        public static string UPDATE_EVENT_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_EVENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest updated.
        /// </summary>
        public static string UPDATE_GUEST_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_GUEST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel booking updated.
        /// </summary>
        public static string UPDATE_HOTEL_BOOKING_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_HOTEL_BOOKING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel updated.
        /// </summary>
        public static string UPDATE_HOTEL_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_HOTEL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization updated.
        /// </summary>
        public static string UPDATE_ORGANIZATION_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_ORGANIZATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationTypes updated.
        /// </summary>
        public static string UPDATE_ORGANIZATIONTYPES_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_ORGANIZATIONTYPES_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment provider updated.
        /// </summary>
        public static string UPDATE_PAYMENT_PROVIDER_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PAYMENT_PROVIDER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated.
        /// </summary>
        public static string UPDATE_PROFILE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff updated.
        /// </summary>
        public static string UPDATE_STAFF_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_STAFF_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription updated.
        /// </summary>
        public static string UPDATE_SUBSCRIPTION_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_SUBSCRIPTION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket updated.
        /// </summary>
        public static string UPDATE_TICKET {
            get {
                return ResourceManager.GetString("UPDATE_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fees updated.
        /// </summary>
        public static string UPDATE_VISA_FEES_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_VISA_FEES_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa status updated.
        /// </summary>
        public static string UPDATE_VISA_STATUS {
            get {
                return ResourceManager.GetString("UPDATE_VISA_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa updated.
        /// </summary>
        public static string UPDATE_VISA_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_VISA_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet updated.
        /// </summary>
        public static string UPDATE_WALLET_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_WALLET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa removed.
        /// </summary>
        public static string VISA_REMOVED {
            get {
                return ResourceManager.GetString("VISA_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa uploaded.
        /// </summary>
        public static string VISA_UPLOADED {
            get {
                return ResourceManager.GetString("VISA_UPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year is required.
        /// </summary>
        public static string YEAR_REQUIRED {
            get {
                return ResourceManager.GetString("YEAR_REQUIRED", resourceCulture);
            }
        }
    }
}
